# Generated by Django 5.0.6 on 2024-07-24 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_recipe_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='url',
        ),
    ]
