# Generated by Django 5.0.6 on 2024-07-24 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_recipe_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
