# Generated by Django 5.0.6 on 2024-07-26 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_recipe_userrecipe'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userrecipe',
            unique_together={('user', 'recipe')},
        ),
    ]
