# Generated by Django 5.0.6 on 2024-07-29 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_userrecipe_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='thumbnail',
            field=models.URLField(default='', max_length=2500),
        ),
        migrations.AddField(
            model_name='recipe',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
